# Generated by Django 3.0.5 on 2021-04-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Details',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.IntegerField(unique=True)),
                ('warehouse_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.CharField(max_length=200)),
                ('order_quantity', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Customer_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('year_Published', models.IntegerField()),
                ('price', models.IntegerField()),
                ('no_of_copies', models.IntegerField()),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author')),
                ('warehouse_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Warehouse_main')),
            ],
        ),
    ]
